Support NO_CONVERTING_ASSIGNMENT macro, to ease Eigen::bfloat test
Allow testing without assuming an assignment operator that converts to bfloat16 (which is not there for `Eigen::bfloat`), by defining `BIOVAULT_BFLOAT16_TEST_NO_CONVERTING_ASSIGNMENT`.

Doing so would avoid the following Visual C++ 2017 compilation errors, when trying to build the unit tests against https://gitlab.com/libeigen/eigen/-/blob/b11f817bcff04276f3024d6780f56a137968b81a/Eigen/src/Core/arch/Default/BFloat16.h

> biovault_bfloat16_test.cpp(159,1): error C2679: binary '=': no operator found which takes a right-hand operand of type 'const T' (or there is no acceptable conversion)
>   with [ T=int ]
>Eigen\src\Core\arch\Default\BFloat16.h(140,1): message : could be 'Eigen::bfloat16 &Eigen::bfloat16::operator =(Eigen::bfloat16 &&)'
>Eigen\src\Core\arch\Default\BFloat16.h(140,1): message : or       'Eigen::bfloat16 &Eigen::bfloat16::operator =(const Eigen::bfloat16 &)'