Support NO_UINT16_AND_BOOL_CONSTRUCTOR macro, to ease Eigen::bfloat test
Allow testing without using the `bfloat16_t::bfloat16_t(uint16_t, bool)` constructor (which is not there for `Eigen::bfloat`), by defining `BIOVAULT_BFLOAT16_TEST_NO_UINT16_AND_BOOL_CONSTRUCTOR`.

Doing so would avoid the following Visual C++ 2017 compilation errors, when trying to build the unit tests against https://gitlab.com/libeigen/eigen/-/blob/b11f817bcff04276f3024d6780f56a137968b81a/Eigen/src/Core/arch/Default/BFloat16.h

> biovault_bfloat16_test.cpp(83,40): error C2440: '<function-style-cast>': cannot convert from 'initializer list' to 'biovault::bfloat16_t'
> biovault_bfloat16_test.cpp(83,40): message : No constructor could take the source type, or constructor overload resolution was ambiguous
> biovault_bfloat16_test.cpp(83,20): error C2064: term does not evaluate to a function taking 2 arguments

and

> biovault_bfloat16_test.cpp(340,55): error C2127: 'bfloat16_from_raw_bits': illegal initialization of 'constexpr' entity with a non-constant expression
> Eigen\src\Core\arch\Default\BFloat16.h(72,8): message : failure was because type 'biovault::bfloat16_t' is not a literal type