Ensure exponent of std::pow is float, to fix VS2019 v16.8 warning C4244
It appears that with Visual C++ 2019 Version 16.8.0, expressions like `std::pow(2.0f, int{ exponent })` return a `double`, while with a previous Visual C++ version, it returned a `float`. This new behavior appears introduced with "Remove pow(floating, int) overloads", pull request https://github.com/microsoft/STL/pull/903  It caused the following warnings:

> biovault_bfloat16_test.cpp(225,37): error C2220: the following warning is treated as an error
> biovault_bfloat16_test.cpp(225,37): warning C4244: 'argument': conversion from 'double' to 'const float', possible loss of data
> biovault_bfloat16_test.cpp(239,37): warning C4244: 'argument': conversion from 'double' to 'const float', possible loss of data

This commit fixes the warnings by making sure that the second argument of `std::pow(2.0f, exponent)` calls is a `float`, instead of an integer.